// <auto-generated />
using System;
using Maliev.AccountingService.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.AccountingService.Data.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20260102140625_CompleteFeatureSet")]
    partial class CompleteFeatureSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.AdjustingEntryApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalComments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("approval_comments");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_adjusting_entry_approvals");

                    b.HasIndex("JournalEntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_adjusting_entry_approvals_journal_entry_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_adjusting_entry_approvals_status");

                    b.ToTable("adjusting_entry_approvals", (string)null);
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.AuditTrailEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("AfterSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_snapshot");

                    b.Property<string>("BeforeSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_snapshot");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_audit_trail_entries");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_trail_entries_correlation_id");

                    b.HasIndex("PerformedBy")
                        .HasDatabaseName("ix_audit_trail_entries_performed_by");

                    b.HasIndex("EntityType", "EntityId", "PerformedAt")
                        .HasDatabaseName("ix_audit_trail_entries_entity_type_entity_id_performed_at");

                    b.ToTable("audit_trail_entries", (string)null);
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.ChartOfAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_number");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_account_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_chart_of_accounts");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_chart_of_accounts_account_number");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_chart_of_accounts_is_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("ParentAccountId")
                        .HasDatabaseName("ix_chart_of_accounts_parent_account_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_chart_of_accounts_type");

                    b.ToTable("chart_of_accounts", (string)null);
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.FinancialPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid>("FiscalYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiscal_year_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_financial_periods");

                    b.HasIndex("FiscalYearId")
                        .HasDatabaseName("ix_financial_periods_fiscal_year_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_financial_periods_status");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("ix_financial_periods_start_date_end_date");

                    b.ToTable("financial_periods", (string)null);
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.FiscalYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("PeriodStructure")
                        .HasColumnType("integer")
                        .HasColumnName("period_structure");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_fiscal_years");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_fiscal_years_name");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("ix_fiscal_years_start_date_end_date");

                    b.ToTable("fiscal_years", (string)null);
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_date");

                    b.Property<string>("EntryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entry_number");

                    b.Property<Guid?>("FinancialPeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("financial_period_id");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<Guid?>("PostedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_by");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_event_id");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_system");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_credit");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_debit");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("EntryDate")
                        .HasDatabaseName("ix_journal_entries_entry_date");

                    b.HasIndex("EntryNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entries_entry_number");

                    b.HasIndex("FinancialPeriodId")
                        .HasDatabaseName("ix_journal_entries_financial_period_id");

                    b.HasIndex("SourceEventId")
                        .HasDatabaseName("ix_journal_entries_source_event_id");

                    b.HasIndex("PeriodId", "Status")
                        .HasDatabaseName("ix_journal_entries_period_id_status");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.JournalEntryLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("credit_amount");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("DebitAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("debit_amount");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<int>("LineSequence")
                        .HasColumnType("integer")
                        .HasColumnName("line_sequence");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_type");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_journal_entry_lines");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_journal_entry_lines_account_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_journal_entry_lines_customer_id");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_journal_entry_lines_journal_entry_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_journal_entry_lines_supplier_id");

                    b.ToTable("journal_entry_lines", (string)null);
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean")
                        .HasColumnName("is_critical");

                    b.HasKey("Code")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "accounting.journal-entries.create",
                            Description = "Create journal entries",
                            IsCritical = false
                        },
                        new
                        {
                            Code = "accounting.journal-entries.read",
                            Description = "Read journal entries",
                            IsCritical = false
                        },
                        new
                        {
                            Code = "accounting.journal-entries.update",
                            Description = "Update journal entries",
                            IsCritical = false
                        },
                        new
                        {
                            Code = "accounting.journal-entries.post",
                            Description = "Post journal entries",
                            IsCritical = true
                        },
                        new
                        {
                            Code = "accounting.journal-entries.reverse",
                            Description = "Reverse journal entries",
                            IsCritical = true
                        },
                        new
                        {
                            Code = "accounting.accounts.create",
                            Description = "Create chart of accounts",
                            IsCritical = false
                        },
                        new
                        {
                            Code = "accounting.accounts.read",
                            Description = "Read account details",
                            IsCritical = false
                        },
                        new
                        {
                            Code = "accounting.accounts.update",
                            Description = "Update accounts",
                            IsCritical = false
                        },
                        new
                        {
                            Code = "accounting.accounts.delete",
                            Description = "Deactivate accounts",
                            IsCritical = false
                        },
                        new
                        {
                            Code = "accounting.accounts.close",
                            Description = "Close accounts",
                            IsCritical = true
                        },
                        new
                        {
                            Code = "accounting.reports.balance-sheet",
                            Description = "View balance sheet",
                            IsCritical = false
                        },
                        new
                        {
                            Code = "accounting.reports.income-statement",
                            Description = "View income statement",
                            IsCritical = false
                        },
                        new
                        {
                            Code = "accounting.reports.cash-flow",
                            Description = "View cash flow statement",
                            IsCritical = false
                        },
                        new
                        {
                            Code = "accounting.reports.trial-balance",
                            Description = "View trial balance",
                            IsCritical = false
                        },
                        new
                        {
                            Code = "accounting.reports.export",
                            Description = "Export financial reports",
                            IsCritical = false
                        },
                        new
                        {
                            Code = "accounting.periods.open",
                            Description = "Open accounting periods",
                            IsCritical = false
                        },
                        new
                        {
                            Code = "accounting.periods.close",
                            Description = "Close accounting periods",
                            IsCritical = true
                        },
                        new
                        {
                            Code = "accounting.periods.reopen",
                            Description = "Reopen closed periods",
                            IsCritical = true
                        },
                        new
                        {
                            Code = "accounting.reconciliation.run",
                            Description = "Run financial reconciliation",
                            IsCritical = true
                        },
                        new
                        {
                            Code = "accounting.reconciliation.read",
                            Description = "Read reconciliation reports",
                            IsCritical = false
                        });
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.ProcessedEventRegistry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id")
                        .HasName("pk_processed_event_registry");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_processed_event_registry_event_id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_processed_event_registry_processed_at");

                    b.ToTable("processed_event_registry", (string)null);
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.ReconciliationReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DiscrepancyDetails")
                        .HasColumnType("jsonb")
                        .HasColumnName("discrepancy_details");

                    b.Property<Guid?>("FinancialPeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("financial_period_id");

                    b.Property<decimal>("GeneralLedgerTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("general_ledger_total");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<string>("ReconciliationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reconciliation_type");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at");

                    b.Property<Guid>("RunBy")
                        .HasColumnType("uuid")
                        .HasColumnName("run_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("SubledgerTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subledger_total");

                    b.Property<decimal>("Variance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("variance");

                    b.HasKey("Id")
                        .HasName("pk_reconciliation_reports");

                    b.HasIndex("FinancialPeriodId")
                        .HasDatabaseName("ix_reconciliation_reports_financial_period_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_reconciliation_reports_status")
                        .HasFilter("status != 'Resolved'");

                    b.HasIndex("PeriodId", "ReconciliationType")
                        .HasDatabaseName("ix_reconciliation_reports_period_id_reconciliation_type");

                    b.ToTable("reconciliation_reports", (string)null);
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.HasKey("Name")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "roles.accounting.admin",
                            Description = "Full access to all accounting operations"
                        },
                        new
                        {
                            Name = "roles.accounting.manager",
                            Description = "General accounting management access"
                        },
                        new
                        {
                            Name = "roles.accounting.clerk",
                            Description = "Basic journal and account data entry"
                        },
                        new
                        {
                            Name = "roles.accounting.controller",
                            Description = "Advanced accounting and period management"
                        },
                        new
                        {
                            Name = "roles.accounting.viewer",
                            Description = "Read-only access to accounting data and reports"
                        });
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.RolePermission", b =>
                {
                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_code");

                    b.HasKey("RoleName", "PermissionCode")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionCode")
                        .HasDatabaseName("ix_role_permissions_permission_code");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.journal-entries.create"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.journal-entries.read"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.journal-entries.update"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.journal-entries.post"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.journal-entries.reverse"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.accounts.create"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.accounts.read"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.accounts.update"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.accounts.delete"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.accounts.close"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.reports.balance-sheet"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.reports.income-statement"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.reports.cash-flow"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.reports.trial-balance"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.reports.export"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.periods.open"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.periods.close"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.periods.reopen"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.reconciliation.run"
                        },
                        new
                        {
                            RoleName = "roles.accounting.admin",
                            PermissionCode = "accounting.reconciliation.read"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.journal-entries.create"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.journal-entries.read"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.journal-entries.update"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.journal-entries.post"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.journal-entries.reverse"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.accounts.create"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.accounts.read"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.accounts.update"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.accounts.delete"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.accounts.close"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.reports.balance-sheet"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.reports.income-statement"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.reports.cash-flow"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.reports.trial-balance"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.reports.export"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.periods.open"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.reconciliation.run"
                        },
                        new
                        {
                            RoleName = "roles.accounting.manager",
                            PermissionCode = "accounting.reconciliation.read"
                        },
                        new
                        {
                            RoleName = "roles.accounting.clerk",
                            PermissionCode = "accounting.journal-entries.create"
                        },
                        new
                        {
                            RoleName = "roles.accounting.clerk",
                            PermissionCode = "accounting.journal-entries.read"
                        },
                        new
                        {
                            RoleName = "roles.accounting.clerk",
                            PermissionCode = "accounting.accounts.read"
                        },
                        new
                        {
                            RoleName = "roles.accounting.clerk",
                            PermissionCode = "accounting.reports.balance-sheet"
                        },
                        new
                        {
                            RoleName = "roles.accounting.clerk",
                            PermissionCode = "accounting.reports.income-statement"
                        },
                        new
                        {
                            RoleName = "roles.accounting.clerk",
                            PermissionCode = "accounting.reports.cash-flow"
                        },
                        new
                        {
                            RoleName = "roles.accounting.clerk",
                            PermissionCode = "accounting.reports.trial-balance"
                        },
                        new
                        {
                            RoleName = "roles.accounting.clerk",
                            PermissionCode = "accounting.reports.export"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.journal-entries.create"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.journal-entries.read"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.journal-entries.update"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.journal-entries.post"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.journal-entries.reverse"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.accounts.create"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.accounts.read"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.accounts.update"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.accounts.delete"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.accounts.close"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.reports.balance-sheet"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.reports.income-statement"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.reports.cash-flow"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.reports.trial-balance"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.reports.export"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.periods.open"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.periods.close"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.periods.reopen"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.reconciliation.run"
                        },
                        new
                        {
                            RoleName = "roles.accounting.controller",
                            PermissionCode = "accounting.reconciliation.read"
                        },
                        new
                        {
                            RoleName = "roles.accounting.viewer",
                            PermissionCode = "accounting.journal-entries.read"
                        },
                        new
                        {
                            RoleName = "roles.accounting.viewer",
                            PermissionCode = "accounting.accounts.read"
                        },
                        new
                        {
                            RoleName = "roles.accounting.viewer",
                            PermissionCode = "accounting.reports.balance-sheet"
                        },
                        new
                        {
                            RoleName = "roles.accounting.viewer",
                            PermissionCode = "accounting.reports.income-statement"
                        },
                        new
                        {
                            RoleName = "roles.accounting.viewer",
                            PermissionCode = "accounting.reports.cash-flow"
                        },
                        new
                        {
                            RoleName = "roles.accounting.viewer",
                            PermissionCode = "accounting.reports.trial-balance"
                        },
                        new
                        {
                            RoleName = "roles.accounting.viewer",
                            PermissionCode = "accounting.reports.export"
                        },
                        new
                        {
                            RoleName = "roles.accounting.viewer",
                            PermissionCode = "accounting.reconciliation.read"
                        });
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.SubledgerTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_system");

                    b.Property<string>("SourceTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_transaction_id");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id")
                        .HasName("pk_subledger_transactions");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_subledger_transactions_journal_entry_id");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("ix_subledger_transactions_transaction_date");

                    b.HasIndex("SourceSystem", "SourceTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_subledger_transactions_source_system_source_transaction_id");

                    b.ToTable("subledger_transactions", (string)null);
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.TaxComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("JournalEntryLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_line_id");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<string>("TaxJurisdiction")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_jurisdiction");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tax_rate");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_type");

                    b.Property<decimal>("TaxableAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("taxable_amount");

                    b.HasKey("Id")
                        .HasName("pk_tax_components");

                    b.HasIndex("JournalEntryLineId")
                        .HasDatabaseName("ix_tax_components_journal_entry_line_id");

                    b.HasIndex("TaxType")
                        .HasDatabaseName("ix_tax_components_tax_type");

                    b.ToTable("tax_components", (string)null);
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.AdjustingEntryApproval", b =>
                {
                    b.HasOne("Maliev.AccountingService.Data.Models.JournalEntry", "JournalEntry")
                        .WithOne("AdjustingEntryApproval")
                        .HasForeignKey("Maliev.AccountingService.Data.Models.AdjustingEntryApproval", "JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_adjusting_entry_approvals_journal_entries_journal_entry_id");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.ChartOfAccount", b =>
                {
                    b.HasOne("Maliev.AccountingService.Data.Models.ChartOfAccount", "ParentAccount")
                        .WithMany("ChildAccounts")
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_chart_of_accounts_chart_of_accounts_parent_account_id");

                    b.Navigation("ParentAccount");
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.FinancialPeriod", b =>
                {
                    b.HasOne("Maliev.AccountingService.Data.Models.FiscalYear", "FiscalYear")
                        .WithMany("FinancialPeriods")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_periods_fiscal_years_fiscal_year_id");

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.JournalEntry", b =>
                {
                    b.HasOne("Maliev.AccountingService.Data.Models.FinancialPeriod", null)
                        .WithMany("JournalEntries")
                        .HasForeignKey("FinancialPeriodId")
                        .HasConstraintName("fk_journal_entries_financial_periods_financial_period_id");

                    b.HasOne("Maliev.AccountingService.Data.Models.FinancialPeriod", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entries_financial_periods_period_id");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.JournalEntryLine", b =>
                {
                    b.HasOne("Maliev.AccountingService.Data.Models.ChartOfAccount", "Account")
                        .WithMany("JournalEntryLines")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entry_lines_chart_of_accounts_account_id");

                    b.HasOne("Maliev.AccountingService.Data.Models.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entry_lines_journal_entries_journal_entry_id");

                    b.Navigation("Account");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.ReconciliationReport", b =>
                {
                    b.HasOne("Maliev.AccountingService.Data.Models.FinancialPeriod", null)
                        .WithMany("ReconciliationReports")
                        .HasForeignKey("FinancialPeriodId")
                        .HasConstraintName("fk_reconciliation_reports_financial_periods_financial_period_id");

                    b.HasOne("Maliev.AccountingService.Data.Models.FinancialPeriod", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reconciliation_reports_financial_periods_period_id");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.RolePermission", b =>
                {
                    b.HasOne("Maliev.AccountingService.Data.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_code");

                    b.HasOne("Maliev.AccountingService.Data.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_name");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.SubledgerTransaction", b =>
                {
                    b.HasOne("Maliev.AccountingService.Data.Models.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_subledger_transactions_journal_entries_journal_entry_id");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.TaxComponent", b =>
                {
                    b.HasOne("Maliev.AccountingService.Data.Models.JournalEntryLine", "JournalEntryLine")
                        .WithMany("TaxComponents")
                        .HasForeignKey("JournalEntryLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tax_components_journal_entry_lines_journal_entry_line_id");

                    b.Navigation("JournalEntryLine");
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.ChartOfAccount", b =>
                {
                    b.Navigation("ChildAccounts");

                    b.Navigation("JournalEntryLines");
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.FinancialPeriod", b =>
                {
                    b.Navigation("JournalEntries");

                    b.Navigation("ReconciliationReports");
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.FiscalYear", b =>
                {
                    b.Navigation("FinancialPeriods");
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.JournalEntry", b =>
                {
                    b.Navigation("AdjustingEntryApproval");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.JournalEntryLine", b =>
                {
                    b.Navigation("TaxComponents");
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Maliev.AccountingService.Data.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
