using Maliev.AccountingService.Api.DTOs.Requests;
using Maliev.AccountingService.Api.DTOs.Responses;
using Maliev.AccountingService.Data.Models;

namespace Maliev.AccountingService.Api.Extensions;

/// <summary>
/// Extension methods for mapping between JournalEntry entities and DTOs
/// </summary>
public static class JournalEntryExtensions
{
    /// <summary>
    /// Maps a JournalEntry entity to a JournalEntryResponse DTO
    /// </summary>
    public static JournalEntryResponse ToResponse(this JournalEntry journalEntry)
    {
        return new JournalEntryResponse
        {
            Id = journalEntry.Id,
            EntryNumber = journalEntry.EntryNumber,
            EntryDate = journalEntry.EntryDate,
            Description = journalEntry.Description,
            Status = journalEntry.Status.ToString(),
            PeriodId = journalEntry.PeriodId,
            PeriodName = journalEntry.Period?.Name,
            TotalDebit = journalEntry.TotalDebit,
            TotalCredit = journalEntry.TotalCredit,
            SourceEventId = journalEntry.SourceEventId != null ? Guid.Parse(journalEntry.SourceEventId) : null,
            Reference = journalEntry.SourceSystem,
            CreatedAt = journalEntry.CreatedAt,
            PostedAt = journalEntry.PostedAt,
            PostedBy = journalEntry.PostedBy,
            Lines = journalEntry.Lines?.Select(l => l.ToResponse()).ToList() ?? new List<JournalEntryLineResponse>()
        };
    }

    /// <summary>
    /// Maps a JournalEntryLine entity to a JournalEntryLineResponse DTO
    /// </summary>
    public static JournalEntryLineResponse ToResponse(this JournalEntryLine line)
    {
        return new JournalEntryLineResponse
        {
            Id = line.Id,
            LineNumber = line.LineSequence,
            AccountId = line.AccountId,
            AccountNumber = line.Account?.AccountNumber ?? string.Empty,
            AccountName = line.Account?.Name ?? string.Empty,
            DebitAmount = line.DebitAmount,
            CreditAmount = line.CreditAmount,
            Description = line.Description,
            CustomerId = line.CustomerId,
            SupplierId = line.SupplierId,
            Reference = line.ReferenceId,
            TaxComponents = line.TaxComponents?.Select(t => t.ToResponse()).ToList()
        };
    }

    /// <summary>
    /// Maps a TaxComponent entity to a TaxComponentResponse DTO
    /// </summary>
    public static TaxComponentResponse ToResponse(this TaxComponent taxComponent)
    {
        return new TaxComponentResponse
        {
            Id = taxComponent.Id,
            TaxType = taxComponent.TaxType,
            TaxRate = taxComponent.TaxRate,
            TaxableAmount = taxComponent.TaxableAmount,
            TaxAmount = taxComponent.TaxAmount
        };
    }

    /// <summary>
    /// Maps an AuditTrailEntry entity to an AuditTrailEntryResponse DTO
    /// </summary>
    public static AuditTrailEntryResponse ToResponse(this AuditTrailEntry entry)
    {
        return new AuditTrailEntryResponse
        {
            Id = entry.Id,
            EntityType = entry.EntityType,
            EntityId = Guid.TryParse(entry.EntityId, out var entityGuid) ? entityGuid : Guid.Empty,
            Operation = entry.Action,
            PerformedBy = entry.PerformedBy,
            PerformedAt = entry.PerformedAt,
            CorrelationId = Guid.TryParse(entry.CorrelationId, out var corrGuid) ? corrGuid : null,
            IpAddress = entry.IpAddress,
            BeforeValue = entry.BeforeSnapshot,
            AfterValue = entry.AfterSnapshot
        };
    }

    /// <summary>
    /// Maps a CreateJournalEntryRequest DTO to a JournalEntry entity
    /// </summary>

    public static JournalEntry ToEntity(this CreateJournalEntryRequest request, Guid periodId, Guid createdBy)
    {
        var journalEntry = new JournalEntry
        {
            Id = Guid.NewGuid(),
            EntryNumber = string.Empty, // Will be generated by service
            EntryDate = request.EntryDate,
            Description = request.Description,
            Status = EntryStatus.Draft,
            PeriodId = periodId,
            SourceSystem = request.Reference,
            CreatedAt = DateTime.UtcNow,
            CreatedBy = createdBy,
            Lines = new List<JournalEntryLine>()
        };

        var lineNumber = 1;
        foreach (var lineRequest in request.Lines)
        {
            journalEntry.Lines.Add(lineRequest.ToEntity(journalEntry.Id, lineNumber++));
        }

        // Calculate totals
        journalEntry.TotalDebit = journalEntry.Lines.Sum(l => l.DebitAmount);
        journalEntry.TotalCredit = journalEntry.Lines.Sum(l => l.CreditAmount);

        return journalEntry;
    }

    /// <summary>
    /// Maps a CreateJournalEntryLineRequest DTO to a JournalEntryLine entity
    /// </summary>
    public static JournalEntryLine ToEntity(this CreateJournalEntryLineRequest request, Guid journalEntryId, int lineNumber)
    {
        var line = new JournalEntryLine
        {
            Id = Guid.NewGuid(),
            JournalEntryId = journalEntryId,
            LineSequence = lineNumber,
            AccountId = request.AccountId,
            DebitAmount = request.DebitAmount,
            CreditAmount = request.CreditAmount,
            Description = request.Description,
            CustomerId = request.CustomerId,
            SupplierId = request.SupplierId,
            ReferenceId = request.Reference,
            TaxComponents = new List<TaxComponent>()
        };

        if (request.TaxComponents != null)
        {
            foreach (var taxRequest in request.TaxComponents)
            {
                line.TaxComponents.Add(taxRequest.ToEntity(line.Id));
            }
        }

        return line;
    }

    /// <summary>
    /// Maps a CreateTaxComponentRequest DTO to a TaxComponent entity
    /// </summary>
    public static TaxComponent ToEntity(this CreateTaxComponentRequest request, Guid journalEntryLineId)
    {
        return new TaxComponent
        {
            Id = Guid.NewGuid(),
            JournalEntryLineId = journalEntryLineId,
            TaxType = request.TaxType,
            TaxRate = request.TaxRate,
            TaxableAmount = request.TaxableAmount,
            TaxAmount = request.TaxAmount
        };
    }
}
